name: Dart CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  analyze:
    runs-on: ubuntu-latest

    container:
      image: dart:latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: dart pub get
      - name: Run static analysis
        run: dart analyze
      - name: Check for automatic fixes
        run: |
          if dart fix --dry-run | grep 'Nothing to fix'; then
            echo "No fixes available."
          else
            echo "Fixes available. Please run 'dart fix' locally and push the changes."
            exit 1
          fi

  test:
    needs: analyze

    runs-on: ubuntu-latest

    container:
      image: dart:latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: dart pub get
      - name: Run tests with code coverage
        run: |
          dart test
  
