name: Dart CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  analyze:
    runs-on: ubuntu-latest
    container:
      image: dart:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: dart pub get

      - name: Run static analysis
        run: dart analyze

      - name: Check for automatic fixes
        run: |
          if dart fix --dry-run | grep 'Nothing to fix'; then
            echo "No fixes available."
          else
            echo "Fixes available. Please run 'dart fix' locally and push the changes."
            exit 1
          fi

      - name: Install necessary tools
        run: |
          apt-get update -y
          apt-get install -y python3-pip lcov
          pip3 install fonttools

      - name: Run tests with coverage
        run: dart test --coverage=./coverage

      - name: Generate LCOV report
        run: dart run coverage:format_coverage --lcov --in=coverage --out=coverage.lcov --report-on=lib

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.lcov
          fail_ci_if_error: true

  deploy:
    needs: analyze
    runs-on: ubuntu-latest
    container:
      image: dart:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          log-public-key: false

      - name: Install rsync
        run: |
          apt-get update -y
          apt-get install -y rsync

      - name: Deploy to server
        run: |
          echo "GMAIL_SMTP_EMAIL=${{ secrets.GMAIL_SMTP_EMAIL_SECRET }}" >> .env
          echo "GMAIL_SMTP_PASSWORD=${{ secrets.GMAIL_SMTP_PASSWORD_SECRET }}" >> .env
          echo "EMAIL_TO=${{ secrets.EMAIL_TO_SECRET }}" >> .env
          dart compile exe bin/football_education_notifier.dart -o bin/football_education_notifier
          rsync -vaz -e "ssh -o StrictHostKeyChecking=no" bin/football_education_notifier ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/srv/football_education_notifier/bin
          rsync -vaz -e "ssh -o StrictHostKeyChecking=no" .env ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/srv/football_education_notifier/
